### PR TITLE
Added new fields in OBF.proto: preciseDx, preciseDy for POI

### PR DESCRIPTION
**Pull request by ivanPyrohivskyi**
Added new fields in OBF.proto: preciseDx, preciseDy for POI

### CODE REVIEW

**Comment by vshcherb** [comment]
Should be POI reading also fixed in iOS?
@PaulStets

**Comment by PaulStets** [comment]
@vshcherb What is the issue that should be fixed? I can test in iOS.

**Comment by vshcherb** [comment]
Perfect alignment between Map UI icons and POI UI icons see below,

image
image

**Comment by PaulStets** [comment]
Can confirm this works on the newest maps in the iOS version.
image

**Comment by vshcherb** [comment]
Haha - it's not implemented yet :-) how did you get the new maps?

**Comment by PaulStets** [comment]
Yep, double-checked and it was only centered for the first place I checked but not for any other place:)

**Comment by ivanPyrohivskyi** [comment]
Impremented precision in 1-xy-xy-xy format

**Comment by vshcherb** [comment]
@PaulStets PR is ready to be merged please test & fix POI together if it's still needed

**Pull request closed without merging**
