### PR TITLE
adding first rudimental CI using github workflow

### PR DESCRIPTION
**Pull request by lightyear15**
please enable CI for this repository so I can test my workflow.
Thanks

### CODE REVIEW

**Comment by vshcherb** [comment]
Will it work? It doesn't have other folders and projects , so it looks a bit strange to me. 
iOS build here - https://github.com/osmandapp/OsmAnd-iOS/blob/master/.github/workflows/xcode-build.yml

**Comment by lightyear15** [comment]
> Will it work? It doesn't have other folders and projects , so it looks a bit strange to me. iOS build here - https://github.com/osmandapp/OsmAnd-iOS/blob/master/.github/workflows/xcode-build.yml

100% it won't, yet we need to make it work I think.
How would you test PRs otherwise? This codebase has to compile and (possibly) run unit tests in isolation. No need for external folders or repositories. As far as I understand this is core, it does not depend on other repositories

**Comment by vshcherb** [comment]
Well you could probably do the runs on the fork first before getting it merged

Yes it needs to compile on your machine so you could test it. Otherwise how could it be merged.

**Comment by lightyear15** [comment]
I am testing CI in my local repository.

By default this CMakeLists.txt does not create any target, which is weird considering that this repository being at the core of all the Osm ecosystem, it should compile with no other dependencies besides optional 3rd party dependencies (like Qt)

The cmake targets are also kinda messed-up IMHO. I am struggling finding a subset of the sources that can be compiled with simple dependencies: even the files in Search subfolder (which should not depend on graphics stuff) depends somehow on skia 2d library.
I think the include directives and header files are so much entangled that everything depends on everything else in here.
I am also struggling isolating a subset of the

**Pull request closed without merging**
